#!/bin/bash

die() {
	zenity --error --title "OLPC Desktop Switcher" --text "Could not switch desktops; an internal error has occurred."
	exit 1
}

zenity --question --title "Switch desktop" --text "Click OK to switch to the Sugar learning environment.\nAll active applications will be closed."
[[ $? != 0 ]] && exit 0

echo "sugar" > ~/.olpc-active-desktop || die
dbus-send --session --dest=org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager.Logout uint32:1 || die
exit 0

